name: Build With Docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string
env:
  DOCKER_NAMESPACE: mystery0
  DOCKER_NAME: version-checker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_NAME }}:${{input.tag}}
